### ISSUE TITLE
Remove unsupported python version in Travis file

### ISSUE THREAD

**Issue by aladjadj** [leboncoin/cassh#9]

**Comment by nbeguier** [comment]
You mean python 2.7 ?

**Comment by aladjadj** [comment]
All Python 3 failed in your pr 10 but fixed in 11 ;)

**Comment by nbeguier** [comment]
hum ? In my pr 10 all travis check passed, isn't it ?

**Comment by aladjadj** [comment]
Sorry PR 8 and fixed in 10
